### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by NatsuSai** [Tsuk1ko/pxder#25]
我尝试过用SocksCap套着用并`disabled proxy`，也试过用`http://127.0.0.1`，都是返回`400`  
![QQ截图20191028012512](https://user-images.githubusercontent.com/18627047/67638797-ac625900-f8e0-11e9-91a6-1eb07319ca29.png)

- [ss](https://github.com/shadowsocks/shadowsocks-windows) version: `4.1.7.1`
- config
```
[1] Download path       X:\Pictures\pixiv
[2] Download thread     5
[3] Download timeout    30
[4] Auto rename         On
[5] Proxy               socks://127.0.0.1:1080
[0] Exit
```
- logs
```
{ Error: Request failed with status code 400
    at createError (C:\Users\user\AppData\Roaming\npm\node_modules\pxder\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\user\AppData\Roaming\npm\node_modules\pxder\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\user\AppData\Roaming\npm\node_modules\pxder\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url: 'https://oauth.secure.pixiv.net/auth/token',
     method: 'post',
     data:
      'client_id=KzEZED7aC0vird8jWyHM38mXjNTY&client_secret=W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP&get_secure_url=1&include_policy=true&grant_type=password&username=username&password=password',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/x-www-form-urlencoded',
        'App-OS': 'ios',
        'Accept-Language': 'en-us',
        'App-OS-Version': '12.0.1',
        'App-Version': '7.2.2',
        'User-Agent': 'PixivIOSApp/7.2.2 (iOS 12.0.1; iPhone8,2)',
        'X-Client-Time': '2019-10-27T17:34:38.938Z',
        'X-Client-Hash': '27a188e3af28f218197cc3379d6c4a65',
        'Content-Length': 205 },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     httpsAgent:
      SocksProxyAgent {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _promisifiedCallback: true,
        timeout: null,
        options: [Url],
        proxy: [Object],
        callback: [Function] } },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'oauth.secure.pixiv.net',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: [Socket],
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 19,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'oauth.secure.pixiv.net',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: [TLSWrap],
        _parent: [Socket],
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [TLSWrap],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 19,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'POST /auth/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nApp-OS: ios\r\nAccept-Language: en-us\r\nApp-OS-Version: 12.0.1\r\nApp-Version: 7.2.2\r\nUser-Agent: PixivIOSApp/7.2.2 (iOS 12.0.1; iPhone8,2)\r\nX-Client-Time: 2019-10-27T17:34:38.938Z\r\nX-Client-Hash: 27a188e3af28f218197cc3379d6c4a65\r\nContent-Length: 205\r\nHost: oauth.secure.pixiv.net:443\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      SocksProxyAgent {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _promisifiedCallback: true,
        timeout: null,
        options: [Url],
        proxy: [Object],
        callback: [Function] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/auth/token',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 400,
        statusMessage: 'Bad Request',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl: 'https://oauth.secure.pixiv.net/auth/token',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 205,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'https://oauth.secure.pixiv.net/auth/token' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        'app-os': [Array],
        'accept-language': [Array],
        'app-os-version': [Array],
        'app-version': [Array],
        'user-agent': [Array],
        'x-client-time': [Array],
        'x-client-hash': [Array],
        'content-length': [Array],
        host: [Array] } },
  response:
   { status: 400,
     statusText: 'Bad Request',
     headers:
      { server: 'nginx',
        date: 'Sun, 27 Oct 2019 17:34:38 GMT',
        'content-type': 'application/json',
        'content-length': '78',
        connection: 'close',
        'x-content-type-options': 'nosniff',
        'strict-transport-security': 'max-age=31536000',
        'x-frame-options': 'SAMEORIGIN' },
     config:
      { url: 'https://oauth.secure.pixiv.net/auth/token',
        method: 'post',
        data:
         'client_id=KzEZED7aC0vird8jWyHM38mXjNTY&client_secret=W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP&get_secure_url=1&include_policy=true&grant_type=password&username=username&password=password',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        httpsAgent: [SocksProxyAgent] },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /auth/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nApp-OS: ios\r\nAccept-Language: en-us\r\nApp-OS-Version: 12.0.1\r\nApp-Version: 7.2.2\r\nUser-Agent: PixivIOSApp/7.2.2 (iOS 12.0.1; iPhone8,2)\r\nX-Client-Time: 2019-10-27T17:34:38.938Z\r\nX-Client-Hash: 27a188e3af28f218197cc3379d6c4a65\r\nContent-Length: 205\r\nHost: oauth.secure.pixiv.net:443\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [SocksProxyAgent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/auth/token',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data: { has_error: true, errors: [Object] } },
  isAxiosError: true,
  toJSON: [Function] }
```

**Comment by Tsuk1ko** [comment]
已修复，一会请更新下 pxder
