### ISSUE TITLE
重命名问题

### ISSUE THREAD

**Issue by Skimige** [Tsuk1ko/pxder#35]
``` node
Collecting illusts of 1/1924 uid 34452206 SG

Directory renamed: (34452206)Sg => (34452206)SG
{ Error: ENOTEMPTY: directory not empty, rename 'H:\Pixiv\(34452206)Sg' -> 'H:\Pixiv\(34452206)SG'
    at Object.renameSync (fs.js:616:3)
    at getIllustratorNewDir (D:\Git\pxder\src\downloader.js:284:7)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  errno: -4051,
  syscall: 'rename',
  code: 'ENOTEMPTY',
  path: 'H:\\Pixiv\\(34452206)Sg',
  dest: 'H:\\Pixiv\\(34452206)SG' }
```

**Comment by Tsuk1ko** [comment]
看起来是文件系统对大小写不敏感导致的，我加个判断

**Comment by Tsuk1ko** [comment]
可以更新到 v2.8.3 了
