### ISSUE TITLE
由于某些原因（网络爆炸）生成空 public.json 之后，下次运行会报错

### ISSUE THREAD

**Issue by Skimige** [Tsuk1ko/pxder#36]
```
SyntaxError: C:\Users\{username}\AppData\Roaming\pxder\public.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:742:27)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at PixivFunc.downloadFollowAll (D:\Git\pxder\src\index.js:326:20)
    at handleArgv.then (D:\Git\pxder\bin\pxder:78:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by Skimige** [comment]
辛苦了~！

**Comment by Tsuk1ko** [comment]
不客气，感谢发现问题

（另外有个子依赖有漏洞，而且我又发现一个没处理好的地方，一会再发一版
