### ISSUE TITLE
用npm更新到最新版本2.8.6后使用pxder命令后报错

### ISSUE THREAD

**Issue by zyizhuo** [Tsuk1ko/pxder#41]
`pc3600@pc3600-ubuntu:~$ pxder
/usr/local/lib/node_modules/pxder/node_modules/fs-extra/lib/mkdirs/make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/pxder/node_modules/fs-extra/lib/mkdirs/index.js:3:44)`

**Comment by Tsuk1ko** [comment]
node 版本是否低于 10

**Comment by zyizhuo** [comment]
> node 版本是否低于 10

nodejs升级到stable已解决，谢谢
