### ISSUE TITLE
pixiv 改用新的登录方式，旧方法已拉闸

### ISSUE THREAD

**Issue by Skimige** [Tsuk1ko/pxder#54]
```
https://oauth.secure.pixiv.net/auth/token
Error: Request failed with status code 400
    at createError (/home/runner/pxder/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/runner/pxder/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/runner/pxder/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
ERROR {
    "message": "Request failed with status code 400",
    "config": {}
}

Login fail! Please check your input or proxy setting.

{
  has_error: true,
  errors: {
    system: {
      message: 'Invalid grant_type parameter or parameter missing',
      code: 1508
    }
  },
  error: 'invalid_grant'
}
Done in 5.77s.
```

各大第三方 pixiv 客户端基本也翻车了，所以这个 issue 算是个提醒吧（

**Comment by Tsuk1ko** [comment]
确实，看来是无了 https://github.com/upbit/pixivpy/issues/158

观望一段时间看看有没有解决方法吧，当前唯一可行的方法只有全部替换成网页的 ajax api，使用自行设置 cookie 的方式登录，但这样涉及到 api 调用的部分都要修改了，工作量还是蛮大的，而且逻辑变化过大的话不如直接重写

但由于我自己都没有在使用 pxder 了，懒得继续维护下去，这项目我可能就直接 archive 了

**Comment by Tsuk1ko** [comment]
已支持 OAuth 登录
